
2022-08-08 00:21:48,003 INFO: errors [in /home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/app.py:519]
2022-08-08 00:21:51,056 INFO: errors [in app.py:519]
2022-08-08 00:22:15,986 ERROR: Exception on /venues/4 [GET] [in /home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 115, in show_venue
    for show in venue.shows
AttributeError: 'NoneType' object has no attribute 'shows'
2022-08-08 00:22:37,281 ERROR: Exception on /artists/7 [GET] [in /home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 262, in show_artist
    for show in artist.shows
AttributeError: 'NoneType' object has no attribute 'shows'
2022-08-08 00:45:02,260 ERROR: Exception on /artists/7 [GET] [in /home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emaribeyodn/workspace/alx-fs-nanodegree/cd0046-SQL-and-Data-Modeling-for-the-Web/env/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 262, in show_artist
    for show in artist.shows
AttributeError: 'NoneType' object has no attribute 'shows'
